### ISSUE TITLE
ssh private key no password not working

### ISSUE THREAD

**Issue by rickglyn** [eidottermihi/rpicheck#122]
Can't get app to work with private key used by ConnectBot app on Note 4.

**Comment by eidottermihi** [comment]
What kind of private key is it? Standard OpenSSH / PKCS keys are working.

**Comment by vasyugan** [comment]
Just bitten by the same issue: It seems an ssh password is required. If you leave the ssh password field empty, you can't exit configuration. Or is the password used to unlock the private key instead? If so, where can the app be configured to use a key for login?

**Comment by eidottermihi** [comment]
There is a dropdown in the configuration dialog where you can choose between
- password authentication
- private key auth
- password protected private key auth
Am 30.05.2016 09:14 schrieb "vasyugan" <notifications@github.com>:
