### ISSUE TITLE
sudo commands time out

### ISSUE THREAD

**Issue by hachel** [eidottermihi/rpicheck#124]
Hi there,

when I run sudo commands with rpicheck I get an `ERROR - A transport exception ocurred. Check your connection. Reason: Timeout expired.`.
Other (non-sudo) commands work fine. The sudo-command itself works fine when I run it in a terminal. I've the sudo password saved with my connection.

Any help?

thanks

**Comment by eidottermihi** [comment]
Does the terminal prompt for your sudo password?

If so, you have to provide the sudo password to the command (possible via placeholder).

**Comment by eidottermihi** [comment]
Closing due inactivity.
