### ISSUE TITLE
Stronger SSH encryption

### ISSUE THREAD

**Issue by sniperle** [eidottermihi/rpicheck#125]
Include stronger ssh encryption modes please.

Log with my sshd config:
net.schmizz.sshj.transport.TransportException: Unable to reach a settlement: [diffie-hellman-group14-sha1, diffie-hellman-group1-sha1] and [curve25519-sha256@libssh.org, diffie-hellman-group-exchange-sha256]

**Comment by eidottermihi** [comment]
The app can't force stronger encryption because this is handled by Android, sorry :-/
