### ISSUE TITLE
Support PINE64

### ISSUE THREAD

**Issue by PanderMusubi** [eidottermihi/rpicheck#127]
Please, support PINE64. Contact me for testing.

**Comment by Phoenix1747** [comment]
Why would you need support for your Pine while this app is clearly built to work only with a Raspberry Pi?

**Comment by PanderMusubi** [comment]
The PINE64 platform is eventually not following a path alongside PRi, as was expected by some. Then reusing code would be beneficial. Part of the functionality offered here is now solved for PINE64 with some bash scripts. So, I will close this is this is no longer interesting to explore further. Thanks for your question.

**Comment by PanderMusubi** [comment]
Just out of curiosity, what part of the code here is RPi-specific?

**Comment by Phoenix1747** [comment]
It's RasPi Check not PINE64 Check, why would the dev invest time to support PINE

**Comment by Phoenix1747** [comment]
But arguing about this now is really stupid, so yeah

**Comment by PanderMusubi** [comment]
Not to argue. If it is only in the name/branding, then I know that.

**Comment by eidottermihi** [comment]
The app relies on vcgencmd for example. This is part of the Raspberry Pi
Firmware. So most parts of the Overclocking section wouldn't work on PINE64.

I'm closing this now.

Am 28.08.2017 3:02 nachm. schrieb "Pander" <notifications@github.com>:
