### ISSUE TITLE
Feature request: Be able to set the interval for status check on widget.

### ISSUE THREAD

**Issue by spiral6** [eidottermihi/rpicheck#131]
I don't want the widget checking every 3 min, it is pretty impactful on my battery. I would like it if we could set the interval to every 5, 10, 30, or 60 min, or once a day, or not at all and only update manually.

**Comment by Phoenix1747** [comment]
I don't know what your problem is, but when I place a widget I can choose between following intervals: 5min, 10min, 30min, 1hr, 2hr, 8hr, 1day, own interval.

**Comment by eidottermihi** [comment]
What @Phoenix1747 said

**Comment by spiral6** [comment]
Ah. Thanks for letting me know. There should be a way to change it after you placed the widget, otherwise you have to remove it and place it again to get those options.

**Comment by Phoenix1747** [comment]
It's not that much work to place it again and adjust all settings :P
