### ISSUE TITLE
Report RPi Date/Time

### ISSUE THREAD

**Issue by astro7467** [eidottermihi/rpicheck#143]
Have instances where fake-hwclock has saved a future time and unless I SSH directly will not be aware that the system clock is not being corrected via ntpdate correctly

**Comment by eidottermihi** [comment]
I'm sorry, I don't understand what's the issue here.
What do you expect from the app?

**Comment by astro7467** [comment]
Add a system info element that reports the system date, time & timezone. Minimumal example would be to report the output of 'date' ;
'root@pom:~# date --rfc-2822
Sat, 26 Aug 2017 07:59:52 +0800'
