### ISSUE TITLE
Wi-Fi information is sometimes incorrect, actually it depends on driver/iwconfig output

### ISSUE THREAD

**Issue by Kabuse** [eidottermihi/rpicheck#155]
I have several Raspberrys and the information for the Wi-Fi signal strenght and quality is only correct (in percentage) on my Raspberry Pi 2, which uses an external Edimax Wi-Fi stick.

On my Raspberry Pi 3 and on my Raspberry Pi Zero with build-in Wi-Fi, the wrong information is shown, because iwconfig, which is apparently used to get the information, delivers the strenght in dBm and the quality in x of 70.

So, if the quality is reported 70%, it is actually 100% (70/70). For the strenght, e.g. 39% is actually 39 dBm, and the following conversion should be done, to correctly display it in percentage:

https://stackoverflow.com/questions/15797920/how-to-convert-wifi-signal-strength-from-quality-percent-to-rssi-dbm

**Comment by Kabuse** [comment]
Actually signal strenght in percentage should be determined like described in this pdf:

https://www.google.de/url?sa=t&source=web&rct=j&url=http://madwifi-project.org/attachment/wiki/UserDocs/RSSI/Converting_Signal_Strength.pdf%3Fformat%3Draw&ved=2ahUKEwiAwISyrZHYAhVB2qQKHetPDiMQFjADegQIBxAB&usg=AOvVaw0y6CjUGBBjWgn8cGjva13r

My first suggestion would result in quality in percentage again, not in strenght in percentage.

**Comment by eidottermihi** [comment]
So, if I understand you correctly, the values iwconfig (or /proc/net/wireless) displays, are based on the driver?

e.g. Driver A (like your Edimax Wi-Fi Stick) reports link quality in percentage, Driver B (like your Pi Zero) reports link quality in x of 70.

If thats the case, is it even possible to determine, when you have to convert the value?

Btw: Raspi Check uses the output of /proc/net/wireless [(as described here)](https://hewlettpackard.github.io/wireless-tools/Linux.Wireless.Extensions.html)

**Comment by Kabuse** [comment]
Exactly! Please see the screenshot for comparison, left side RPI2 with an Edimax stick, right side RPI3 with built-in Wi-Fi:

![zwischenablage01](https://user-images.githubusercontent.com/13647006/34122532-096363ee-e42d-11e7-9e67-16e4a78543be.jpg)

I think you can only see the reference values, if you look at the output of iwconfig. You could check the value after the "/" and check if the string "dBm" is present. "x/100" means, you can just use the read value, "x/y" and "dBm" recognized means that you have to do a calculation to get the values for strenght and quality in percentage.

**Comment by eidottermihi** [comment]
Thank you for the screenshot, it says more than a thousand words! 👍 

I'll add this to my TODO list
