### ISSUE TITLE
Attempting to view log force closes

### ISSUE THREAD

**Issue by timread** [eidottermihi/rpicheck#169]
Worked fine on previous version. Now app closes every time I attempt to cute the log. I'm running LineageOS 14.1 on OnePlus One. Raspberry pi3 (cn)

**Comment by eidottermihi** [comment]
Seems like File URIs are no longer supported on API 24 and above: https://medium.com/@ali.muzaffar/what-is-android-os-fileuriexposedexception-and-what-you-can-do-about-it-70b9eb17c6d0

Looking into it....
