### ISSUE TITLE
gradle build failed

### ISSUE THREAD

**Issue by Gursewak00** [eidottermihi/rpicheck#173]
Error:Failed to resolve: com.hierynomus:sshj:0.23.0-ANDROID-COMPAT-2-SNAPSHOT
<a href="openFile:F:/Android downloads/raspberry pi/rpicheck-master/rpicheck-master/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by eidottermihi** [comment]
fixed with 40d02952835d69ba882d5c2d0a02f602471c4374
