### ISSUE TITLE
Unbuildable by F-Droid

### ISSUE THREAD

**Issue by gsantner** [eidottermihi/rpicheck#178]
Hi there, I saw that recently a jar was checked in (for ssh module). This makes the app unbuildable by F-Droid as they only allow to build from source or from mvm repos that provide the source for the jar together with the jar.

Is there any way the jar could be removed and instead the lib be loaded from e.g. mavencentral or jitpack? Should be easy possible, ala `compile 'com.hierynomus:sshj:0.25.0'` - see <https://search.maven.org/#artifactdetails%7Ccom.hierynomus%7Csshj%7C0.25.0%7Cjar> for other versions

Btw, F-Droid is currently on the state of `1.8.0`, don't know what happened since that. <https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/de.eidottermihi.raspicheck.txt>

Thank you!

**Comment by eidottermihi** [comment]
Thanks for reminding, the jar was a temporarily workaround for as long as sshj version >= 0.24 wasn't released. As this is no longer the case, I will switch to the official release (and will look into F-Droid metadata).

**Comment by eidottermihi** [comment]
fixed in 0e76097a090a491dc358f9c3412f33f862ead0da, v1.8.10

**Comment by PanderMusubi** [comment]
@eidottermihi see https://github.com/eidottermihi/rpicheck/issues/195 for metadata

Other question, see can you add versionName as is mentioned in https://gitlab.com/fdroid/fdroiddata/-/issues/1988#note_311073711 so that F-Droid can build new releases automatically?
