### ISSUE TITLE
Feature request - Custom commands on the main screen

### ISSUE THREAD

**Issue by 1nikolas** [eidottermihi/rpicheck#182]
Hello. It will be very useful to add custom commands on the main screen. It's easier than telling you adding a bunch of commands to show usefull (at least for me) things. Also you can add the ability to change or disable/remove commands or edit them
Thanks in advance.

**Comment by Ione75** [comment]
I'll try thanks

**Comment by eidottermihi** [comment]
This is a dupliate of #79
