### ISSUE TITLE
RasPi Check for Ubuntu?

### ISSUE THREAD

**Issue by odoooooo** [eidottermihi/rpicheck#191]
Hi, I already usw this nice tool/app for my raspberry (raspbian) sucessfully.

But I also have another machine (Ubuntu on a amd64 chip), that I want to monitor.

Is there a way to use RasPi Check for my Ubuntu amd64 machine or is there another/comparable tool or app?

**Comment by good4y0u** [comment]
see issue #161

**Comment by emma-goldman** [comment]
sudo apt install libraspberrypi-bin
sudo usermod video _ssh_user_

(Haven't tried it but found a reference to this package on an arch thread)

**Comment by eidottermihi** [comment]
closing, see #161
