### ISSUE TITLE
Feature request: support for local proxy

### ISSUE THREAD

**Issue by n1m1** [eidottermihi/rpicheck#197]
Hello and thanks for your excellent work.

Would you consider to add a support for local HTTP and SOCKS5 proxy, please?

I would like to use rpicheck with Orbot in order to connect to few ssh onion-instances. 

I am not a coder and I do not know at all if this can be helpful, but [DavX5](https://gitlab.com/bitfireAT/davx5-ose) has already implemented a similar support in their client.

Cheers.

**Comment by eidottermihi** [comment]
This would require support for proxies in sshj, which is not available: https://github.com/hierynomus/sshj/issues/324
