### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [eidottermihi/rpicheck#201]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by eidottermihi** [comment]
I'm not sure what the current state of Bouncycastle on Android is. It was already tricky to get it working with spongycastle, so not quite sure where to start first here.

But I'll happily accept PRs for this.

**Comment by eidottermihi** [comment]
Seems like SpongyCastle could be replaced with official BouncyCastle according to

https://github.com/rtyley/spongycastle/issues/34 https://github.com/rtyley/spongycastle/issues/34#issuecomment-292687789
