### ISSUE TITLE
Feature request show type of Raspberry Pi

### ISSUE THREAD

**Issue by PanderMusubi** [eidottermihi/rpicheck#209]
Bases on the ID, show if the device is type 1, 2, 3, 4 or zero and if it is A, B or +. See https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md

Should not result in an error when there is no ID or the lookup fails.

**Comment by eidottermihi** [comment]
I'll happily accept pull requests for this.
