### ISSUE TITLE
Feature Request: Configure Wlan Settings

### ISSUE THREAD

**Issue by mrcg** [eidottermihi/rpicheck#43]
It would be really helpful to have the possibility to configure the wlan settings to connect to wifi network (e.g. add new wifi network ... ssid, psk, ....).
More or less GUI to confire wpa-supplicant.
If possible it should also support .... scan for wifi networks .... and the select one of the found network to add it to the config.

Due to the fact that Raspberry is used quite often in areas were no LAN and no Screen is availabe such feature would be really helpful.

**Comment by eidottermihi** [comment]
Closing this because I think RasPi Check should be a slim tool to check on your Pi and run simple commands, and no configuration utility.
To configure a Raspberry Pi I would suggest sticking to normal SSH clients.
