### ISSUE TITLE
Transport Exception

### ISSUE THREAD

**Issue by Ellargo333** [eidottermihi/rpicheck#58]
Hi. I have a problem trying to access my raspi.

" A transport exception occurred. " appears when trying to check stats.

I use juicessh and it connects just fine.

I am using no-ip to connect

What could be the problem?

**Comment by eidottermihi** [comment]
Can't help without feedback.

**Comment by marshevms** [comment]
https://gist.github.com/marshevms/978a146e83e43e049d3737e8cbfd0137

**Comment by marshevms** [comment]
```
[rpi4@rpi4 ~]$ ssh -G rpi4 | grep kexalgorithms
kexalgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256

```

**Comment by marshevms** [comment]
#214
