### ISSUE TITLE
Sending commands

### ISSUE THREAD

**Issue by Viskovitz** [eidottermihi/rpicheck#62]
Hello, when I try to send a command (ie. shutdown -r now) I have this messsage:

Connecting to host 192.168.1.13 ...
Authenticating with password ...
Connection established.
ERROR - A transport exception occured. Check your connection.
Reason: Timeout expired

I setup the sudo password for that connection in rpicheck and I check the connection from another computer via ssh and it is ok.

Any idea about what could be happen? Must I to setup something in my raspberry?

Greetings.

**Comment by eidottermihi** [comment]
Can't help without feedback.

**Comment by Viskovitz** [comment]
Sorry Michael, I was a little messy and didn't had much time...

Anyway it seems to be a problem in my Arch. A few weeks ago I changed to
Raspbian and RasPi Check works perfect.


Greetings and sorry again.

2015-03-14 16:16 GMT+01:00 Michael Prankl <notifications@github.com>:

**Comment by JinnLin** [comment]
I also met this issue

Connection established.
ERROR - A transport exception  occured. Check your connection.
Reason: Timeout expired

through by Internet to run "yunpatch" shell program.  use the PuTTY, the program yunpatch can run smoothly, but use RasPi Check , got the "Timeout expired" ...

I enable the "Debug logging", please refer the attach file.
[RasPiCheck-log.txt](https://github.com/eidottermihi/rpicheck/files/1239436/RasPiCheck-log.txt)

**Comment by eidottermihi** [comment]
I think the problem here is the default timeout of 20 seconds currently in place for sending commands:

https://github.com/eidottermihi/rpicheck/blob/3ae511488d34ddd98381d0e40482a48693f905e2/ssh/src/main/java/de/eidottermihi/rpicheck/ssh/impl/RaspiQuery.java#L1213-L1215

How long does "yunpatch" usually need to finish? If its longer than 20 seconds, the timeout kicks in.

**Comment by JinnLin** [comment]
yes, it is over 20 secconds.

it is PHP web site in customers' site.   yunpatch will connect to my server to do the patches update...
I check the fault site, yunpatch cost 25 seconds, and verify another customer site, another cost 11 seconds. I think it is network bandwith issue in fault site. 

How can I change the default timeout of 20 seconds ??

**Comment by JinnLin** [comment]
Thanks a lot.

I am a newer of github and not a mobile phone developer. what do i do to install the revision in my mobile phone ? Will the revision be updated in Android Store ?

**Comment by eidottermihi** [comment]
You should get an update via Play Store in the next 24 hours.
Alternatively you can install the APK directly, https://github.com/eidottermihi/rpicheck/releases/tag/v1.8.1

**Comment by JinnLin** [comment]
Thanks for this great, great helpness.

this APK solves my problem, will inform my friends to upgrade the new version from Play Store.

Can i have a little suggestion ?  can provide any "progress" indication when run this kind long command ?
Customer has no patient to wait...
