### ISSUE TITLE
Banned from Google Play store?

### ISSUE THREAD

**Issue by poll0rz** [eidottermihi/rpicheck#69]
https://play.google.com/store/apps/details?id=de.eidottermihi.rpicheck

![image](https://cloud.githubusercontent.com/assets/2879742/6166221/88d77d4e-b2ae-11e4-919a-aa2f39c3345a.png)

**Comment by eidottermihi** [comment]
Will be back soon, was removed because of violation of Raspberry Pi Foundation registered trademark (logo)...

**Comment by poll0rz** [comment]
still banned. any news please?
i liked the app and some friends want it.
thanks!

**Comment by cbamofkd** [comment]
@eidottermihi
Can you please provide an alternative download until its back in the Play Store?
Publishing it in F-Droid would be even better!

**Comment by eidottermihi** [comment]
Sorry guys, I can't get Google to reinstate the app, it's really frustrating. They refuse to reinstate the "old app" with changed logo etc. and also refuse to publish the "new app" (with new app package).

In the meantime I uploaded the [most recent version to Droidbin](http://www.droidbin.com/p19flrc15e1f071d8fs9d7ih1i8i3). Beware that the application has a new app package, so you have to add your Pi's again....

**Comment by eidottermihi** [comment]
It's back online, but with different package name:

https://play.google.com/store/apps/details?id=de.eidottermihi.raspicheck
