### ISSUE TITLE
List processes OpenElec 5.0.3 empty

### ISSUE THREAD

**Issue by ruudmeesters** [eidottermihi/rpicheck#70]
Recently added a Pi 1 B running OpenElec 5.0.3 and noticed that the list of processes at the bottom of the overview is empty.

**Comment by eidottermihi** [comment]
Have you unchecked "Hide root processes" in settings?
Am 27.02.2015 10:41 schrieb "ruudmeesters" <notifications@github.com>:

**Comment by ruudmeesters** [comment]
Great, that works. Thanks. Nice app,  Michael.

Ruud

Verzonden vanaf mijn Sony Xperia™-smartphone

---- Michael Prankl schreef ----
