### ISSUE TITLE
Store logs in sdcard/Android/data instead sdcard/data

### ISSUE THREAD

**Issue by ogarcia** [eidottermihi/rpicheck#84]
The correct behaviour is that the app store our files into sdcard/Android/data instead use sdcard/data directly.

I think that only change https://github.com/eidottermihi/rpicheck/blob/master/app/src/main/assets/logback.xml#L2 and https://github.com/eidottermihi/rpicheck/blob/master/app/src/main/java/de/eidottermihi/rpicheck/activity/helper/Constants.java#L24 must be sufficient.

**Comment by eidottermihi** [comment]
Why is sdcard/Android/data better in your opinion?

If we change this, you would need to implement some backward compability to open the old logs.

**Comment by ogarcia** [comment]
Cause is the "Android Way":tm: :smile: and all other apps store their info in that folder. If in yor Adroid device you open sdcard/Android/data you can see a lot of folders with configs/logs/etc of several apps.

There is some references to this:
- In official docs: http://developer.android.com/reference/android/content/Context.html#getExternalFilesDir(java.lang.String)
- In github (different methods to obtain proper directory): https://gist.github.com/granoeste/5574148
- In stackexchange: http://android.stackexchange.com/questions/47924/where-android-apps-store-data
